import { subDays, subHours, subMinutes, subSeconds } from "date-fns";

const now = new Date();

export const chefs = [
  {
    id: "5e887ac47eed253091be10cb",
    phone: "0384 513 222",
    avatarUrl: "/assets/avatars/avatar-carson-darrin.png",
    city: "Cleveland",
    country: "USA",
    currency: "$",
    email: "carson.darrin@devias.io",
    hasAcceptedMarketing: true,
    isProspect: false,
    isReturning: true,
    fullName: "Carson Darrin",
    state: "Ohio",
    totalSpent: 300.0,
    totalOrders: 3,
    totalFeedbacks: 5,
    wallet: 100.0,
    rating: 4.5,
    updatedAt: subDays(subHours(now, 7), 1).getTime(),
  },
  {
    id: "5e887b209c28ac3dd97f6db5",
    avatarUrl: "/assets/avatars/avatar-fran-perez.png",
    phone: "0131 654 123",
    city: "Atlanta",
    country: "USA",
    currency: "$",
    email: "fran.perez@devias.io",
    hasAcceptedMarketing: true,
    isProspect: true,
    isReturning: false,
    fullName: "Fran Perez",
    state: "Georgia",
    totalSpent: 0.0,
    totalOrders: 0,
    totalFeedbacks: 0,
    wallet: 0.0,
    rating: 0.0,
    updatedAt: subDays(subHours(now, 1), 2).getTime(),
  },
  {
    id: "5e887b7602bdbc4dbb234b27",
    avatarUrl: "/assets/avatars/avatar-jie-yan-song.png",
    phone: "078 7173 9265",
    city: "North Canton",
    country: "USA",
    currency: "$",
    email: "jie.yan.song@devias.io",
    hasAcceptedMarketing: false,
    isProspect: false,
    isReturning: false,
    fullName: "Jie Yan Song",
    state: "Ohio",
    totalSpent: 5600.0,
    totalOrders: 6,
    totalFeedbacks: 10,
    wallet: 200.0,
    rating: 4.0,
    updatedAt: subDays(subHours(now, 4), 2).getTime(),
  },
  {
    id: "5e86809283e28b96d2d38537",
    avatarUrl: "/assets/avatars/avatar-anika-visser.png",
    phone: "087 552 9328",
    city: "Madrid",
    country: "Spain",
    currency: "$",
    email: "anika.visser@devias.io",
    hasAcceptedMarketing: true,
    isProspect: false,
    isReturning: true,
    fullName: "Anika Visser",
    state: "Madrid",
    totalSpent: 500.0,
    totalOrders: 1,
    totalFeedbacks: 2,
    wallet: 50.0,
    rating: 3.0,
    updatedAt: subDays(subHours(now, 11), 2).getTime(),
  },
  {
    id: "5e86805e2bafd54f66cc95c3",
    avatarUrl: "/assets/avatars/avatar-miron-vitold.png",
    phone: "087 552 9328",
    city: "San Diego",
    country: "USA",
    currency: "$",
    email: "miron.vitold@devias.io",
    hasAcceptedMarketing: true,
    isProspect: true,
    isReturning: false,
    fullName: "Miron Vitold",
    totalSpent: 0.0,
    totalOrders: 0,
    state: "California",
    totalFeedbacks: 0,
    wallet: 0.0,
    rating: 0.0,
    updatedAt: subDays(subHours(now, 7), 3).getTime(),
  },
];
